# -*- Mode: CMake; indent-tabs-mode: nil; c-basic-offset: 4; tab-width: 4 -*- */

INCLUDE(CMakeParseArguments REQUIRED)

MACRO(EMBED_GENERATE)

    SET(SINGLE_OPTIONS DESTINATION PREFIX MODULE)

    cmake_parse_arguments(EMBED "" "${SINGLE_OPTIONS}" "FILES" ${ARGN})

    IF ("${EMBED_MODULE}" STREQUAL "")
        SET(EMBED_MODULE "embedded")
    ENDIF()

    SET(RESOURCE_FILE "${EMBED_DESTINATION}/${EMBED_MODULE}.c")
    SET(HEADER_FILE "${EMBED_DESTINATION}/${EMBED_MODULE}.h")

    FILE(WRITE "${RESOURCE_FILE}" "// Autogenerated file, do not edit!\n#include <string.h>\n#include \"${EMBED_MODULE}.h\"\nchar* _${EMBED_MODULE}[] = { \n")

    FOREACH(EMBED_FILE ${EMBED_FILES})

        GET_FILENAME_COMPONENT(EMBED_NAME "${EMBED_FILE}" NAME)

        FILE(READ "${EMBED_FILE}" CONTENT)
        STRING(REPLACE "\\" "\\\\" CONTENT "${CONTENT}")
        STRING(REPLACE "\n" "\\n" CONTENT "${CONTENT}")
        STRING(REPLACE "\"" "\\\"" CONTENT "${CONTENT}")
        FILE(APPEND "${RESOURCE_FILE}" " \"${EMBED_PREFIX}${EMBED_NAME}\", \"${CONTENT}\", \n")

    ENDFOREACH(EMBED_FILE)

    FILE(APPEND "${RESOURCE_FILE}" " \"\" \n }; \n")

    FILE(APPEND "${RESOURCE_FILE}" "\nconst char* ${EMBED_MODULE}_get(const char* name) { int i = 0; while (_${EMBED_MODULE}[i][0]) { if (strcmp(name, _${EMBED_MODULE}[i]) == 0) return _${EMBED_MODULE}[i+1]; else i += 2; } return NULL; }")

    FILE(WRITE "${HEADER_FILE}" "// Autogenerated file, do not edit!\n#ifndef __${EMBED_MODULE}_H\n#define __${EMBED_MODULE}_H\n#ifdef __cplusplus\nextern \"C\" {\n#endif\nconst char* ${EMBED_MODULE}_get(const char* name);\n#ifdef __cplusplus\n}\n#endif\n#endif\n")  

ENDMACRO(EMBED_GENERATE)
